<a href="https://colab.research.google.com/github/ahmedebeed555/deeplearning/blob/main/24Aug2025Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

torch.__version__

'2.8.0+cu126'

In [15]:
scaler = torch.tensor(5)


scaler
scaler.ndim

0

In [16]:
scaler.shape

torch.Size([])

In [17]:
vector = torch.tensor([1,2,3])

vector

tensor([1, 2, 3])

In [18]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([3])

In [21]:
MyMatrix = torch.tensor([[1,2],[3,4]])

MyMatrix

tensor([[1, 2],
        [3, 4]])

In [22]:
MyMatrix.ndim

2

In [24]:
MyMatrix.shape

torch.Size([2, 2])

In [43]:
MyTensor = torch.tensor([[[1,2,3,5,5],[4,5,6,2,2],[7,8,9,4,4],[1,2,3,1,1]]])

MyTensor

tensor([[[1, 2, 3, 5, 5],
         [4, 5, 6, 2, 2],
         [7, 8, 9, 4, 4],
         [1, 2, 3, 1, 1]]])

In [44]:
MyTensor.ndim

3

In [45]:
MyTensor.shape

torch.Size([1, 4, 5])

In [47]:
random_tensor = torch.rand(size=(2,5,4))

random_tensor

tensor([[[0.3100, 0.5665, 0.0917, 0.2903],
         [0.5766, 0.1028, 0.7844, 0.1912],
         [0.6401, 0.7083, 0.8427, 0.2298],
         [0.9545, 0.7656, 0.9796, 0.5309],
         [0.7001, 0.9245, 0.5164, 0.5592]],

        [[0.4521, 0.9162, 0.9366, 0.0409],
         [0.1426, 0.6651, 0.6347, 0.7518],
         [0.6721, 0.5828, 0.5282, 0.7875],
         [0.3103, 0.6763, 0.1511, 0.9925],
         [0.8441, 0.9758, 0.4534, 0.1311]]])

In [48]:
random_tensor.ndim

3

In [49]:
random_tensor.size

<function Tensor.size>

In [70]:
# define random seed
torch.manual_seed(42)

# create random tensor
random_matrix = torch.rand(size=(5,5))

random_matrix

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317, 0.1053]])

In [51]:
random_matrix.ndim

2

In [52]:
random_matrix.shape

torch.Size([5, 5])

In [71]:
torch.ones(size=(3,4))    # white image

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [72]:
torch.zeros(size=(3,4))   # black image

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [89]:
torch.manual_seed(42)

tensor1 = torch.rand(size=[5,5])
tensor2 = torch.rand(size=[5,3])

tensor1 @ tensor2    # matrix multiplication


tensor([[1.4441, 1.6540, 1.9579],
        [0.8001, 1.7553, 1.4161],
        [1.5037, 1.9796, 1.8400],
        [1.3006, 1.2317, 1.6317],
        [0.7125, 1.0938, 1.1636]])

In [90]:
tensor1.matmul(tensor2)

tensor([[1.4441, 1.6540, 1.9579],
        [0.8001, 1.7553, 1.4161],
        [1.5037, 1.9796, 1.8400],
        [1.3006, 1.2317, 1.6317],
        [0.7125, 1.0938, 1.1636]])

In [96]:
tensor2.multiply(tensor1)

RuntimeError: The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 1

In [97]:
torch.nn.Linear(in_features = 2 , out_features = 5)

Linear(in_features=2, out_features=5, bias=True)

In [101]:
tesnor_a = torch.tensor([   [3,4],
                     [2,5],
                     [1,3]
                          ]    , dtype=torch.float)

In [111]:
linear = torch.nn.Linear(in_features=2, out_features=1)
linear(tesnor_a)

tensor([[-3.6428],
        [-3.6491],
        [-2.3576]], grad_fn=<AddmmBackward0>)