<a href="https://colab.research.google.com/github/ahmedebeed555/deeplearning/blob/main/24Aug2025Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

torch.__version__

'2.8.0+cu126'

In [15]:
scaler = torch.tensor(5)


scaler
scaler.ndim

0

In [16]:
scaler.shape

torch.Size([])

In [17]:
vector = torch.tensor([1,2,3])

vector

tensor([1, 2, 3])

In [18]:
vector.ndim

1

In [19]:
vector.shape

torch.Size([3])

In [21]:
MyMatrix = torch.tensor([[1,2],[3,4]])

MyMatrix

tensor([[1, 2],
        [3, 4]])

In [22]:
MyMatrix.ndim

2

In [24]:
MyMatrix.shape

torch.Size([2, 2])

In [27]:
MyTensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

MyTensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [28]:
MyTensor.ndim

3

In [29]:
MyTensor.shape

torch.Size([1, 3, 3])