<a href="https://colab.research.google.com/github/ahmedebeed555/deeplearning/blob/main/29Aug2025DeepLearningPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn


In [2]:
!nvidia-smi

Fri Aug 29 15:02:33 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
torch.cuda.is_available()

True

In [4]:
# this command checks the runtime device ( CPU or GPU ) and names the device accordingly
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
tensor = torch.rand(size=(3, 4))


In [6]:
tensor.shape , tensor.ndim

(torch.Size([3, 4]), 2)

In [7]:
tensor_on_GPU = tensor.to(device)
tensor_on_GPU

tensor([[0.1222, 0.3763, 0.3403, 0.1310],
        [0.3859, 0.4182, 0.4553, 0.1722],
        [0.6817, 0.8301, 0.7281, 0.0585]], device='cuda:0')

In [8]:
tensor_back_on_CPU = tensor_on_GPU.cpu().numpy()
tensor_back_on_CPU

array([[0.12223804, 0.3762592 , 0.34025413, 0.13099903],
       [0.38593906, 0.41822922, 0.45529103, 0.17220509],
       [0.6817012 , 0.8301222 , 0.72813225, 0.05852461]], dtype=float32)

In [9]:
linear = nn.Linear(in_features=2,out_features=100)

In [10]:
tensor = torch.rand(size=(6,2))

In [11]:
tensor.to("cuda")

tensor([[0.4511, 0.9530],
        [0.8506, 0.8463],
        [0.1423, 0.4337],
        [0.6499, 0.9244],
        [0.4857, 0.7760],
        [0.6629, 0.9817]], device='cuda:0')

In [12]:
linear(tensor)

tensor([[ 0.3448, -0.1450, -0.6636, -0.5579, -0.5899, -0.6011,  0.2002, -0.0724,
          0.3324,  0.2968,  0.0284, -0.4763,  0.4600, -0.0926, -0.2376,  0.3961,
         -0.6085,  0.0762,  0.2619, -0.7114, -0.0051, -0.2834, -1.1232, -0.3187,
          0.3066,  0.4987,  0.3578,  0.2079,  0.6284,  0.9610, -0.3659,  0.0399,
         -0.5115,  0.5952, -0.4335, -0.6712,  0.2523, -0.0780, -0.0397,  0.8159,
          0.9062, -0.9894,  0.2692,  0.1419, -0.1903,  0.0090,  0.4124,  1.1711,
          0.3959, -0.4575, -0.8822,  0.3114,  1.1075, -0.4068, -0.9017, -0.2342,
         -0.7299, -0.4679,  0.2781, -0.8092,  0.2146,  0.4152, -0.1853,  0.1054,
          1.2935,  0.3274,  0.0471, -0.6348, -1.2704, -0.0073, -0.0186,  0.7246,
         -0.1528,  0.0291,  0.6453, -0.2098,  0.8749, -0.3629,  0.0942,  0.0978,
          0.0480, -0.2457,  0.2147,  0.1987, -0.3588,  0.5715, -0.2892, -0.3694,
         -0.7599,  0.1707, -0.1213,  0.8328,  1.0248, -0.1479,  0.6252, -0.1791,
         -0.6506, -0.2511, -